### ISSUE TITLE
toggle controls

### ISSUE THREAD

**Issue by jovo** [neurodata/ndviz#25]
- they are all histogram controls, so maybe label that box 'histogram', or use a histogram icon
- incorporate windowing, which is already supported on the backend

**Comment by alexbaden** [comment]
I think this is mostly done. There might be an opportunity to explore windowing directly in ndv later, but being able to change the backend window through ndv isn't great because it will result in a ton of requests on the backend (especially when using tilecache). Better to properly window with the restful args. Maybe we could build a little ndv applet that loaded a single PNG from OCP w/ the restful args exposed as form fields?

**Comment by alexbaden** [comment]
Controls in v2 are totally different and a bit more minimalistic. And also in a more logical place (the layer dropdown). Still some work to do reducing the size of the header menu bar, but the overall screen view is much less cluttered now.
